FROM ubuntu:focal

RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python3 \
        python3-venv \
    && rm -rf /var/lib/apt/lists/*

WORKDIR src
ENV PATH=/venv/bin:$PATH

COPY requirements.txt .
RUN : \
    && python3 -m venv /venv \
    && pip install --disable-pip-version-check --no-cache-dir -r requirements.txt

COPY . .

